remove version from package json

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -92,8 +92,11 @@ jobs:
       - run:
           name: Set version from git tag
           command: |
-            TAG=${CIRCLE_TAG}
-            npm version $TAG --no-git-tag-version --allow-same-version
+            if [ -z "$CIRCLE_TAG" ]; then
+              echo "Error: No git tag found. This job should only run on tagged commits."
+              exit 1
+            fi
+            npm version $CIRCLE_TAG --no-git-tag-version --allow-same-version
       - run:
           name: Authenticate with npm
           command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
@@ -156,7 +159,7 @@ workflows:
             - build
           filters:
             tags:
-              only: /^v.*/
+              only: /^[0-9]+\.[0-9]+\.[0-9]+.*/
             branches:
               ignore: /.*/
           context: npm-publish
