Improvement: Include Git Tag in version in circleci publish step & update instructions in readme.md (#12)
Include Git Tag in version in circleci publish step & update instructions in readme.md

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -90,6 +90,14 @@ jobs:
       - attach_workspace:
           at: .
       - run:
+          name: Set version from git tag
+          command: |
+            if [ -z "$CIRCLE_TAG" ]; then
+              echo "Error: No git tag found. This job should only run on tagged commits."
+              exit 1
+            fi
+            npm version $CIRCLE_TAG --no-git-tag-version --allow-same-version
+      - run:
           name: Authenticate with npm
           command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
       - run:
@@ -151,7 +159,7 @@ workflows:
             - build
           filters:
             tags:
-              only: /^v.*/
+              only: /^[0-9]+\.[0-9]+\.[0-9]+.*/
             branches:
               ignore: /.*/
           context: npm-publish
